services:
  
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    volumes:
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  frontend:
    build: frontend
    container_name: vite-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend:
    build: backend
    container_name: laravel-backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mydb
      DB_USERNAME: laravel_user
      DB_PASSWORD: mypassword
    depends_on:
      - db
    ports:
      - "8000:9000"  # Forward port 9000 (PHP-FPM) to host's port 8000
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: task-zantu-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret  # Change this!
      PMA_HOST: task-zantu-db
      MYSQL_DATABASE: mydb
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge